createproject:
	python -m django startproject mysite .

runserver:
	python manage.py runserver

startapp:
	python manage.py startapp polls

makemigrations:
	python manage.py makemigrations polls

migrate:
	python manage.py migrate

sqlmigrate:
	python manage.py sqlmigrate polls 0001

shell:
	python manage.py shell

createsuperuser:
	python manage.py createsuperuser