name: hw01 Pylint/pytest workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./hw_01/requirements.txt
        pip install black
        pip install pylint
        pip install pytest
    - name: Analysing code with pylint and black
      run: |
        pylint --disable=C0103,C0114,C0116,C0115 --fail-under=7 ./hw_01/log_interpreter.py
        black ./hw_01/log_interpreter.py
        pytest -v ./hw_01/tests/test_log_parser.py
