name: mypy check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13' # use the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run mypy
      run: mypy --ignore-missing-imports ./hw_02/basic.py ./hw_02/intermediate.py
