name: HW_04 Pylint/Black/Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install pylint
        pip install pytest
    - name: Analysing the code with pylint and black and testing
      run: |
        pylint --disable=C0103,C0114,C0116,C0115 --fail-under=7 ./hw_04/api/api.py
        black ./hw_04/api/api.py
        pytest ./hw_04/api/test.py
        
