name: HW_06 Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install pylint
        pip install pytest
        pip install -r ./hw_06/api/requirements.txt
  
    - name: Testing workout
      run: |
        pylint --disable=C0103,C0114,C0116,C0115 --fail-under=7 ./hw_06/api/*.py
        black ./hw_06/api/*.py
        pytest ./hw_06/api/tests/test_infrastructure/test_orm.py
        pytest ./hw_06/api/tests/test_domain/test_services.py	
